apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: webapp
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec: # Pod spec
      serviceAccountName: webapp-sa
      containers:
      - name: webapp
        image: arokiyasneka/reactapp:v1.0
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: html-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-storage
          persistentVolumeClaim:
            claimName: webapp-pvc