apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: flask
  selector:
    app: webapp
    tier: frontend
  type: NodePort
